name: Continuous Integration

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: app/go.mod

      - name: Download Dependencies
        run: go mod download

      - name: Verify Formatting
        run: gofmt -l .

      - name: Run Go Vet
        run: go vet ./...

      - name: Run Tests
        run: go test ./...

      - name: Build Application
        run: go build ./...